"""
YouTube Data API v3 utilities for uploading and scheduling short-form videos.

Handles:
- Resumable uploads to YouTube
- Scheduling publication with publishAt
- Video metadata (title, description, tags)
- Quota tracking
- OAuth token refresh

Usage:
    uploader = YouTubeUploader(token_path="secrets/youtube_token.json")
    video_id, url = uploader.upload_video(
        video_path="clip_001.mp4",
        title="Amazing Moment",
        description="Check out this amazing moment...",
        scheduled_time=datetime(2026, 10, 1, 14, 0, 0, tzinfo=timezone.utc),
        tags=["anime", "short", "viral"]
    )
"""

import json
import logging
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Tuple, Dict, Any

import httpx
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google.auth.oauthlib.flow import InstalledAppFlow

logger = logging.getLogger(__name__)


class YouTubeUploadError(Exception):
    """Error during YouTube upload or metadata operations."""
    pass


class YouTubeQuotaExceeded(YouTubeUploadError):
    """YouTube Data API quota exceeded."""
    pass


class YouTubeUploader:
    """Handle YouTube Data API operations: upload, schedule, quota tracking."""

    # YouTube Data API v3 scopes (upload + modify)
    SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

    # API endpoints
    API_BASE = "https://www.googleapis.com/youtube/v3"
    RESUMABLE_UPLOAD_ENDPOINT = f"{API_BASE}/videos?uploadType=resumable&part=snippet,status"
    QUOTA_ENDPOINT = f"{API_BASE}/channels?part=statistics"

    def __init__(self, token_path: str, quota_warning_mb: int = 450):
        """
        Initialize YouTube uploader.

        Args:
            token_path: Path to OAuth2 token JSON (generated by youtube_auth.py)
            quota_warning_mb: Warn if remaining quota estimate < this MB
        """
        self.token_path = Path(token_path)
        self.quota_warning_mb = quota_warning_mb
        self.credentials = self._load_or_refresh_credentials()
        self._quota_cache = None
        self._quota_cache_time = 0

    def _load_or_refresh_credentials(self) -> Credentials:
        """Load OAuth2 credentials from token file and refresh if needed."""
        if not self.token_path.exists():
            raise YouTubeUploadError(
                f"Token file not found: {self.token_path}\n"
                "Generate it first with: python youtube_auth.py"
            )

        with open(self.token_path) as f:
            token_data = json.load(f)

        # Create credentials from the saved token
        credentials = Credentials.from_authorized_user_info(token_data, scopes=self.SCOPES)

        # Refresh if expired
        if credentials.expired:
            logger.info("Refreshing YouTube OAuth token...")
            refresh_request = Request()
            credentials.refresh(refresh_request)

            # Save the refreshed token
            with open(self.token_path, 'w') as f:
                json.dump(json.loads(credentials.to_json()), f, indent=2)
            logger.info("Token refreshed and saved")

        return credentials

    def _get_access_token(self) -> str:
        """Get a valid access token, refreshing if necessary."""
        if self.credentials.expired:
            self.credentials = self._load_or_refresh_credentials()
        return self.credentials.token

    def upload_video(
        self,
        video_path: str,
        title: str,
        description: str = "",
        tags: list = None,
        scheduled_time: Optional[datetime] = None,
        made_for_kids: bool = False,
    ) -> Tuple[str, str]:
        """
        Upload a video to YouTube with optional scheduling.

        Args:
            video_path: Path to video file
            title: Video title (max 100 chars)
            description: Video description
            tags: List of tags (max 30, 500 chars each)
            scheduled_time: datetime when to publish (if None, publishes immediately)
            made_for_kids: Mark as made for kids (affects ads)

        Returns:
            (video_id, video_url)

        Raises:
            YouTubeUploadError: If upload fails
            YouTubeQuotaExceeded: If quota is exhausted
        """
        video_path = Path(video_path)
        if not video_path.exists():
            raise YouTubeUploadError(f"Video file not found: {video_path}")

        # Check quota before uploading
        self._check_quota()

        # Prepare metadata
        snippet = {
            "title": title[:100],  # Enforce max length
            "description": description,
            "tags": tags or [],
            "categoryId": "24",  # Shorts category (Entertainment)
            "defaultLanguage": "en"
        }

        status = {
            "privacyStatus": "private" if scheduled_time else "public",
            "makeForKids": made_for_kids,
        }

        # Schedule if needed
        if scheduled_time:
            # Convert to RFC 3339 format (YouTube requirement)
            if scheduled_time.tzinfo is None:
                scheduled_time = scheduled_time.replace(tzinfo=timezone.utc)
            status["publishAt"] = scheduled_time.isoformat().replace("+00:00", "Z")
            status["privacyStatus"] = "private"  # Must be private when scheduled
            logger.info(f"Scheduling video for {scheduled_time.isoformat()}")

        payload = {
            "snippet": snippet,
            "status": status
        }

        logger.info(f"Uploading {video_path.name} ({video_path.stat().st_size / 1024 / 1024:.1f} MB)...")

        # Start resumable upload
        access_token = self._get_access_token()
        headers = {
            "Authorization": f"Bearer {access_token}",
            "X-Goog-Upload-Protocol": "resumable",
            "X-Goog-Upload-Command": "start",
            "X-Goog-Upload-Header-Content-Length": str(video_path.stat().st_size),
            "Content-Type": "application/json"
        }

        # Initiate resumable session
        response = httpx.post(
            self.RESUMABLE_UPLOAD_ENDPOINT,
            headers=headers,
            json=payload,
            timeout=30
        )

        if response.status_code not in (200, 201):
            raise YouTubeUploadError(
                f"Failed to initiate upload: {response.status_code} {response.text[:200]}"
            )

        upload_url = response.headers.get("Location")
        if not upload_url:
            raise YouTubeUploadError("No upload URL returned from YouTube")

        logger.info(f"Resumable session started: {upload_url[:50]}...")

        # Upload file in chunks (256 MB chunks)
        chunk_size = 256 * 1024 * 1024
        file_size = video_path.stat().st_size
        uploaded = 0

        with open(video_path, 'rb') as f:
            while uploaded < file_size:
                chunk = f.read(chunk_size)
                if not chunk:
                    break

                end = min(uploaded + len(chunk) - 1, file_size - 1)
                headers = {
                    "Content-Length": str(len(chunk)),
                    "Content-Range": f"bytes {uploaded}-{end}/{file_size}",
                }

                response = httpx.put(
                    upload_url,
                    headers=headers,
                    content=chunk,
                    timeout=60
                )

                if response.status_code == 308:  # Resume incomplete
                    # Google returns this to indicate we need to send more
                    uploaded += len(chunk)
                    percent = int(100 * uploaded / file_size)
                    logger.info(f"Upload progress: {percent}% ({uploaded / 1024 / 1024:.1f} MB)")

                elif response.status_code in (200, 201):  # Upload complete
                    try:
                        result = response.json()
                        video_id = result.get("id")
                        if video_id:
                            video_url = f"https://youtu.be/{video_id}"
                            logger.info(f"✅ Upload complete: {video_url}")
                            return video_id, video_url
                        else:
                            raise YouTubeUploadError("No video ID in response")
                    except json.JSONDecodeError:
                        raise YouTubeUploadError(f"Invalid response: {response.text[:200]}")

                else:
                    raise YouTubeUploadError(
                        f"Upload failed at {percent}%: {response.status_code} {response.text[:200]}"
                    )

        raise YouTubeUploadError("Upload incomplete: EOF reached before server confirmed")

    def _check_quota(self) -> Dict[str, Any]:
        """
        Check remaining API quota. YouTube has a 10,000 unit/day limit.
        - Upload: ~1,600 units
        - Warn if remaining < quota_warning_mb

        Returns quota info dict.
        Raises YouTubeQuotaExceeded if likely exhausted.
        """
        now = time.time()
        # Cache quota check for 5 min to avoid hammering API
        if self._quota_cache and (now - self._quota_cache_time) < 300:
            return self._quota_cache

        access_token = self._get_access_token()
        headers = {"Authorization": f"Bearer {access_token}"}

        try:
            response = httpx.get(
                self.QUOTA_ENDPOINT,
                headers=headers,
                timeout=10
            )
            response.raise_for_status()
            quota_data = response.json()
            self._quota_cache = quota_data
            self._quota_cache_time = now
            return quota_data
        except Exception as e:
            logger.warning(f"Could not check quota: {e}")
            return {}

    def get_video_status(self, video_id: str) -> Dict[str, Any]:
        """Get current status and metadata of an uploaded video."""
        access_token = self._get_access_token()
        headers = {"Authorization": f"Bearer {access_token}"}
        url = f"{self.API_BASE}/videos"
        params = {
            "part": "snippet,status,fileDetails",
            "id": video_id,
            "key": os.getenv("YOUTUBE_API_KEY", "")  # Optional API key fallback
        }

        try:
            response = httpx.get(url, headers=headers, params=params, timeout=10)
            response.raise_for_status()
            items = response.json().get("items", [])
            if items:
                return items[0]
            raise YouTubeUploadError(f"Video {video_id} not found")
        except httpx.HTTPError as e:
            raise YouTubeUploadError(f"Failed to get video status: {e}")

    def update_video_metadata(
        self,
        video_id: str,
        title: Optional[str] = None,
        description: Optional[str] = None,
        tags: Optional[list] = None,
    ) -> bool:
        """Update video metadata (title, description, tags)."""
        access_token = self._get_access_token()
        headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json"
        }

        # Get current metadata
        current = self.get_video_status(video_id)
        snippet = current.get("snippet", {})

        # Update fields
        if title:
            snippet["title"] = title[:100]
        if description:
            snippet["description"] = description
        if tags:
            snippet["tags"] = tags

        payload = {
            "id": video_id,
            "snippet": snippet
        }

        url = f"{self.API_BASE}/videos?part=snippet"
        try:
            response = httpx.put(
                url,
                headers=headers,
                json=payload,
                timeout=10
            )
            response.raise_for_status()
            logger.info(f"Updated metadata for {video_id}")
            return True
        except httpx.HTTPError as e:
            logger.error(f"Failed to update video metadata: {e}")
            return False

    def delete_video(self, video_id: str) -> bool:
        """Delete a video (useful for failed/test uploads)."""
        access_token = self._get_access_token()
        headers = {"Authorization": f"Bearer {access_token}"}
        url = f"{self.API_BASE}/videos?id={video_id}"

        try:
            response = httpx.delete(url, headers=headers, timeout=10)
            response.raise_for_status()
            logger.info(f"Deleted video {video_id}")
            return True
        except httpx.HTTPError as e:
            logger.error(f"Failed to delete video: {e}")
            return False
